version: "1.0"
info:
  model: int-scaffold
packages:
- name: TestGitFeatureProject
  gitServerName: testGitFeatureExtAccount
  gitUrl: https://github.com/PoojaAnandGit/TestGitFeatureProject
  gitUsername: PoojaAnandGit
  gitBranch: main
services:
- serviceName: project.testgitfeature.integrations:testEdgeFlow
  packages:
  - name: TestGitFeatureProject
    version: "1.0"
- serviceName: pub.date:getCurrentDate
  packages:
  - name: WmPublic
    version: 11.0.0.0.840
